export type Branch = "foundation" | "signal" | "data" | "system" | "ai";

export type KnowledgeNode = {
  id: string;
  title: string;
  subtitle: string;
  branch: Branch;
  parent?: string;
  summary: string;
  details?: string[];
  formula?: string;
  impact?: string;
  verification?: string;
  pitfall?: string;
};

export type FormulaSymbol = {
  symbol: string;
  latex: string;
  explanation: string;
  unit?: string;
};

export type FormulaMeta = {
  latex: string;
  symbols: FormulaSymbol[];
};

export const branchMeta: Record<Branch, { label: string; color: string }> = {
  foundation: { label: "波形与中频机理", color: "#23b5a5" },
  signal: { label: "中频信号处理", color: "#ff8a4c" },
  data: { label: "检测后数据处理", color: "#8b75ff" },
  system: { label: "系统与硬件约束", color: "#d1a82d" },
  ai: { label: "AI 与学习方法", color: "#ed6f9b" },
};

const k = (
  id: string, title: string, subtitle: string, branch: Branch, parent: string | undefined,
  summary: string, extra: Partial<Omit<KnowledgeNode, "id" | "title" | "subtitle" | "branch" | "parent" | "summary">> = {},
): KnowledgeNode => ({ id, title, subtitle, branch, parent, summary, ...extra });

export const knowledgeNodes: KnowledgeNode[] = [
  k("fmcw", "FMCW 雷达知识图谱", "波形 → IF → 检测 → 航迹", "foundation", undefined,
    "FMCW 雷达连续发射线性调频 chirp，将回波与本振混频得到低频拍频。距离、径向速度和到达角分别编码在快时间频率、慢时间相位演化和阵列通道相位差中。",
    { details: ["ADC 数据先形成 [接收通道, chirp, sample] 数据立方体。", "典型处理链为距离 FFT、速度 FFT、检测、测角、聚类、关联与跟踪。"] }),

  k("foundation", "波形与中频形成", "RF 回波如何变成 ADC 数据", "foundation", "fmcw",
    "这一分支描述 chirp 参数、传播时延、去斜混频和离散采样之间的定量关系。"),
  k("chirp", "线性调频 Chirp", "f(t)=f₀+St", "foundation", "foundation",
    "一个上升 chirp 在持续时间 Tc 内以近似恒定斜率 S 扫过带宽 B，S=B/Tc。目标回波是发射信号的延时、衰减和多普勒偏移版本。",
    { formula: "S = B / T_c", impact: "B 主要决定距离分辨率；Tc、chirp 周期和 chirp 数共同约束最大速度、速度分辨率与帧率。" }),
  k("tx-phase", "Chirp 相位是频率的积分", "φ(t)=2π(f₀t+St²/2)", "foundation", "chirp",
    "瞬时频率是相位对时间的导数，因此线性扫频对应二次相位。推导拍频时必须从相位相减，而不能只把两个瞬时频率机械相减。",
    { formula: "s_tx(t)=A·exp{j2π(f₀t+½St²)}", pitfall: "忽略相位常数项会丢失多普勒和跨 chirp 相位信息。" }),
  k("slope", "调频斜率 S", "MHz/µs 决定拍频尺度", "foundation", "chirp",
    "同一距离产生的距离拍频与 S 成正比。增大斜率可以把目标能量移到更高 IF，但也要求更高 ADC 采样率和模拟 IF 带宽。",
    { formula: "f_r = 2SR/c", impact: "斜率过小会压缩不同距离目标的频率间隔；过大可能使远端目标超出 IF/ADC 通带。" }),
  k("range-resolution", "距离分辨率由带宽决定", "ΔR=c/(2B)", "foundation", "chirp",
    "两个等强点目标能否在距离维分开，主要取决于有效调频带宽 B，而不是 FFT 点数。4 GHz 带宽对应约 3.75 cm 的理想距离分辨率。",
    { formula: "ΔR = c / (2B)", verification: "用两个角反射器逐步减小间距，统计双峰可分辨的最小间距；同时报告所用窗函数。", pitfall: "把零填充后的 bin 间隔误称为分辨率。" }),
  k("dechirp", "去斜混频把时延变成拍频", "高频差分 → 低频 IF", "foundation", "foundation",
    "接收信号与当前发射 chirp 的共轭相乘，再经低通滤波，载频附近的和频项被移除，保留与传播时延和多普勒有关的拍频。",
    { details: ["静止点目标在单 chirp 内近似为一个复正弦。", "多个目标的 IF 是多个复正弦叠加，并叠加噪声、泄漏和硬件杂散。"] }),
  k("beat-range", "静止目标：拍频映射距离", "R≈cf_b/(2S)", "foundation", "dechirp",
    "在窄带、多普勒可忽略的近似下，传播往返时延 τ=2R/c，去斜后距离拍频 f_b≈Sτ，因此可由频率估计距离。",
    { formula: "τ=2R/c；f_b≈Sτ；R≈cf_b/(2S)", verification: "用已知距离角反射器拟合 range index 到米的线性关系，并估计固定 range bias。" }),
  k("range-doppler-coupling", "单 Chirp 拍频含距离与速度", "f_b≈2SR/c+2v/λ", "foundation", "dechirp",
    "运动目标的 IF 频率同时包含距离项和多普勒项。只凭单个上升 chirp 无法严格分离二者；多 chirp 慢时间处理或不同斜率波形用于解耦。",
    { formula: "f_b ≈ 2SR/c + f_D，f_D=2v/λ", pitfall: "高速目标若直接按静止目标公式映射，会产生距离偏差。" }),
  k("if-band", "IF 带宽限制最大可测距离", "f_b 必须落在模拟与数字通带", "foundation", "dechirp",
    "远距离或大斜率目标产生更高拍频。最大距离不仅由 ADC Nyquist 频率决定，还受模拟 LPF、HPF、接收增益和器件可用 IF 带宽限制。",
    { impact: "HPF 会抑制近距离静态泄漏，也可能衰减真正的近距离目标；LPF 与采样率共同限制远端。", verification: "扫动单目标距离，检查幅度随 IF 频率的通带响应，而不是只看是否出现峰值。" }),
  k("data-cube", "ADC 数据立方体", "Rx × Chirp × Sample", "foundation", "foundation",
    "快时间 sample 轴承载距离频率，慢时间 chirp 轴承载多普勒相位，Rx/虚拟阵元轴承载到达角相位。处理维度弄错会得到看似有峰但物理含义错误的结果。"),
  k("fast-slow-time", "快时间与慢时间", "sample 内测距，chirp 间测速", "foundation", "data-cube",
    "对每个 chirp 的 ADC sample 做距离 FFT；随后固定一个距离单元，沿连续 chirp 做 Doppler FFT。两次 FFT 的采样间隔不同，对应不同的物理频率。",
    { verification: "检查数据 shape、内存步长、chirp 时间戳和帧内丢 chirp；用单目标验证峰只在预期二维单元移动。" }),
  k("complex-iq", "复数 I/Q 保留正负频率", "相位用于速度与测角", "foundation", "data-cube",
    "复采样保留相位和频率符号，使正负径向速度可区分。只取幅度或实部会破坏慢时间相位、阵列相位以及后续相参积累。",
    { pitfall: "I/Q 交换、共轭方向或符号约定错误会翻转速度轴或角度轴。" }),

  k("signal", "中频信号处理", "IF 数据 → 稳定检测点", "signal", "fmcw",
    "这一分支包含距离、速度、角度、检测与射频非理想抑制，目标是从 ADC 数据中得到带不确定度的量测。"),
  k("range-processing", "距离维处理", "每个 Chirp 的快时间谱", "signal", "signal",
    "距离维处理通常包含直流/静态泄漏抑制、窗函数、FFT、幅度或功率计算以及 bin 到米的标定。"),
  k("dc-removal", "直流与近距泄漏抑制", "减均值 / 高通 / 泄漏模板", "signal", "range-processing",
    "TX-RX 耦合、LO 泄漏和静态反射会在零拍频附近形成强分量。逐 chirp 减均值抑制 DC，但也可能削弱极近距离或跨帧稳定的真实回波。",
    { verification: "无目标暗室数据观察零频附近功率；加入近距离角反射器检查目标保留率。" }),
  k("range-window", "加窗以旁瓣换主瓣", "Hann 降旁瓣但展宽主瓣", "signal", "range-processing",
    "有限长度 FFT 相当于矩形截断，非整 bin 正弦会发生谱泄漏。Hann、Taylor、Chebyshev 等窗降低旁瓣，但扩大等效噪声带宽并降低峰值增益。",
    { impact: "弱目标靠近强目标时通常更需要低旁瓣；两个近距离等强目标则更关心主瓣宽度。", verification: "同时报告 3 dB 主瓣宽度、峰值旁瓣比 PSLR 和 ENBW。" }),
  k("range-fft", "Range FFT 将拍频离散化", "k→f_k→R_k", "signal", "range-processing",
    "N 点 FFT 的频率栅格为 Δf=Fs/N。结合斜率 S 后，距离 bin 间隔为 cFs/(2SN)，但真实可分辨能力仍由有效带宽和窗函数决定。",
    { formula: "f_k=kFs/N；R_k=cf_k/(2S)", pitfall: "未执行 FFT shift 或正负频率选择错误会造成距离轴异常。" }),
  k("zero-padding", "零填充只细化谱采样", "更密的 bin ≠ 更高分辨率", "signal", "range-processing",
    "在时域尾部补零等价于对原有 DTFT 做更密采样，可改善峰值显示和插值初值，但不会增加观测带宽，也不能把物理上不可分的两目标分开。",
    { impact: "可减小粗栅格量化误差，却不会降低主瓣宽度。" }),
  k("doppler-processing", "速度维处理", "跨 Chirp 的相位斜率", "signal", "signal",
    "固定距离单元后，运动目标在连续 chirp 间产生近似线性相位增长。Doppler FFT 将该相位斜率转换为径向速度。"),
  k("doppler-phase", "速度来自跨 Chirp 相位差", "Δφ=4πvTᵣ/λ", "signal", "doppler-processing",
    "相邻 chirp 起始时刻相隔 Tr，往返路程变化 2vTr，对应相位变化 Δφ=4πvTr/λ。相位只在 ±π 内无歧义。",
    { formula: "v = λΔφ/(4πT_r)", pitfall: "chirp 时间戳不是 ramp 时间；必须包含 idle time。" }),
  k("doppler-fft", "Doppler FFT 形成速度谱", "慢时间 FFT", "signal", "doppler-processing",
    "对同一距离单元的多个 chirp 做慢时间窗和 FFT。速度分辨率与总相干观测时间近似成反比，chirp 数增加可缩窄多普勒主瓣但降低更新率。",
    { impact: "帧内观测时间越长，速度分辨率越高；机动目标的速度变化会造成谱展宽。" }),
  k("velocity-ambiguity", "最大无模糊速度由慢时间采样决定", "|v|<λ/(4Tᵣ)", "signal", "doppler-processing",
    "慢时间采样率为 1/Tr，其 Nyquist 区间对应最大无模糊径向速度。超出后速度折返到相反或较小的 Doppler bin。",
    { formula: "v_max = λ/(4T_r)", impact: "缩短 Tr 提高无模糊速度，但可能挤压可用采样时间并增加系统时序压力。" }),
  k("coherent-integration", "相参积累先对齐相位再求和", "理想功率增益约 N", "signal", "doppler-processing",
    "若 N 个快拍的目标相位可预测，复数对齐后求和使信号幅度按 N 增长、独立噪声功率按 N 增长，因此输出 SNR 理想提升 N 倍。",
    { pitfall: "目标跨 bin、相位噪声或模型失配会造成失相干，实际增益低于理论值。", verification: "随积累数 N 画输出 SNR 曲线，并与 10log10(N) dB 理论线比较。" }),
  k("detection", "自适应目标检测", "功率单元 → 门限判决", "signal", "signal",
    "检测器比较待检测单元 CUT 与局部背景估计乘缩放因子后的门限。核心不是找峰，而是在给定虚警率约束下最大化检测概率。"),
  k("nci-pci", "非相参、部分相参与相参积累", "NCI / PCI / CI", "signal", "detection",
    "CI 在复数域保持相位；NCI 对幅度或功率累加，不需要精确相位但增益较低；PCI 将数据分段相参后再非相参合并，用于折中相位稳定性与增益。"),
  k("cfar-geometry", "CFAR 训练单元与保护单元", "训练估背景，保护隔离目标泄漏", "signal", "detection",
    "CUT 两侧或周围的训练单元用于估计噪声/杂波功率，保护单元避免目标主瓣和旁瓣污染背景估计。窗口尺寸必须与主瓣宽度和背景平稳尺度匹配。",
    { pitfall: "保护单元过少会抬高门限漏检；训练区过大可能跨越杂波边缘。" }),
  k("ca-cfar", "CA-CFAR 用局部均值估计背景", "均匀噪声中效率高", "signal", "detection",
    "CA-CFAR 对训练单元功率求均值，再乘由 Pfa 和训练单元数确定的系数。均匀指数噪声中接近最优，但多目标和杂波边缘会污染均值。",
    { formula: "T=α·mean(P_train)", verification: "纯噪声 Monte Carlo 统计实测 Pfa；扫 SNR 得到 Pd 曲线。" }),
  k("os-cfar", "OS-CFAR 用第 k 个有序样本", "对干扰目标更稳健", "signal", "detection",
    "OS-CFAR 将训练功率排序并选第 k 个样本作为背景尺度。通过忽略若干最大样本减轻邻近干扰目标污染，但需要排序且参数 k 依赖场景。",
    { impact: "比 CA-CFAR 更能承受训练窗内少量强目标，代价是均匀背景中的额外检测损失和更高计算量。" }),
  k("pd-pfa", "Pd 与 Pfa 必须成对报告", "检测率不能脱离虚警率", "signal", "detection",
    "降低门限可以提高检测率 Pd，但同时提高虚警率 Pfa。比较检测器时必须在相同 Pfa 或完整 ROC 条件下比较，而不是只报召回率。",
    { verification: "使用独立无目标样本估计 Pfa，并给出置信区间；使用有目标样本按 SNR 分桶统计 Pd。" }),
  k("spectrum", "精细谱估计", "从 FFT 粗峰到亚栅格参数", "signal", "signal",
    "FFT 提供稳定粗估计；插值、稀疏重构和子空间方法可降低栅格误差或分辨近邻目标，但更依赖模型、快拍数、校准和计算资源。"),
  k("sva", "SVA 自适应抑制旁瓣", "逐频点调节余弦窗系数", "signal", "spectrum",
    "Spatially Variant Apodization 在频域为不同频点选择局部窗系数，目标是在保持接近矩形窗分辨率的同时抑制旁瓣。必须处理分母接近零和噪声放大。"),
  k("peak-interpolation", "谱峰插值获得亚 bin 估计", "利用峰及相邻 bin", "signal", "spectrum",
    "抛物线、Jacobsen 等插值利用主峰邻域的幅相关系估计真实频率偏移。对单一高 SNR 正弦有效，但窗函数、邻近目标和低 SNR 会引入偏差。",
    { verification: "随机扫过一个 bin 内的真实频率，绘制估计偏差和 RMSE 随 SNR 的曲线。" }),
  k("music", "MUSIC 用噪声子空间形成伪谱", "aᴴEₙEₙᴴa 越小峰越高", "signal", "spectrum",
    "对协方差矩阵特征分解后，真实方向的导向矢量与噪声子空间近似正交。MUSIC 可超越 FFT 栅格，但需要目标数估计、足够快拍和准确阵列流形。",
    { formula: "P_MUSIC(θ)=1/[aᴴ(θ)E_nE_nᴴa(θ)]", pitfall: "相干多径会使信号协方差降秩，常需空间平滑。" }),
  k("iaa-omp-relax", "IAA / OMP / RELAX 的模型差异", "迭代加权 / 稀疏贪心 / 逐目标优化", "signal", "spectrum",
    "IAA 迭代更新谱功率与协方差；OMP 在离散字典上逐次选择原子；RELAX 交替重估各正弦参数。三者都可能提升近邻分辨，但对字典失配、停止条件和算力敏感。"),
  k("angle", "到达角估计", "阵列相位差 → 方位/俯仰", "signal", "signal",
    "远场平面波到达不同阵元时产生与阵元位置投影相关的相位差。阵列几何、波长、通道校准和有效孔径共同决定角度视场与分辨率。"),
  k("steering-vector", "阵列导向矢量", "a_m(θ)=e^{j2πp_m sinθ/λ}", "signal", "angle",
    "导向矢量描述给定方向在各阵元上的理论复响应。非均匀阵列必须使用真实阵元坐标，不能直接套用均匀阵列 FFT。",
    { formula: "a_m(θ)=exp(j2πp_m sinθ/λ)" }),
  k("angle-fft", "均匀线阵可用空间 FFT 测角", "空间频率 u=d sinθ/λ", "signal", "angle",
    "ULA 阵元序列是空间采样信号，FFT 将空间频率映射为角度。角度 bin 在 sinθ 域均匀，因此靠近端射方向的角度误差和栅格间距更大。",
    { pitfall: "FFT 点数增加只插值空间谱；真实角分辨率取决于有效孔径。" }),
  k("grating-lobe", "阵元间距过大产生栅瓣", "d>λ/2 时可能空间混叠", "signal", "angle",
    "当不同方向产生相同阵元相位序列时出现空间混叠。λ/2 间距支持最大的无模糊视场；稀疏阵列需借助非均匀几何或先验处理栅瓣。"),
  k("channel-calibration", "通道幅相误差会扭曲角谱", "校准残差直接形成角偏差与旁瓣", "signal", "angle",
    "不同 RX/TX 链路的增益和相位偏差会使实际导向矢量偏离模型。常用已知方位角反射器估计每通道复系数，再在测角前补偿。",
    { verification: "多距离、多温度重复测量 boresight 角偏差、通道幅相残差和角谱旁瓣。" }),
  k("nonideal", "非理想因素与伪目标", "泄漏、相噪、杂散、量化、多径", "signal", "signal",
    "硬件与传播非理想会制造固定频点、裙带噪声、镜像峰或几何鬼影。抑制前必须先区分随机噪声、确定性杂散和真实多径。"),
  k("phase-noise", "相位噪声形成强目标裙带", "近距离强反射可抬高邻频噪底", "signal", "nonideal",
    "本振相位随机扰动经去斜后表现为目标附近的谱扩展。它与目标功率相关，因此远处弱目标可能被近处强目标的相噪裙带遮蔽。",
    { verification: "单强目标场景测量不同频偏处 dBc/Hz 或功率谱密度，并与无目标噪底区分。" }),
  k("spurs", "确定性杂散表现为稳定频点", "跨帧频率位置稳定", "signal", "nonideal",
    "PLL、时钟、数字耦合或电源纹波可在 IF 中产生窄带杂散。与真实目标相比，它们常对天线通道、温度或配置呈固定模式。",
    { impact: "简单静态 notch 可抑制已知 spur，但会永久损失对应距离/速度单元的目标可见度。" }),
  k("quantization", "量化噪声与削顶是两类失真", "ENOB 决定有效动态范围", "signal", "nonideal",
    "小信号受量化噪声影响，过大信号则造成 ADC 削顶并产生宽带谐波/杂散。VGA 增益应在噪声利用率与峰值余量之间折中。",
    { verification: "统计 ADC 码直方图、满量程占用、削顶比例和无目标噪声 RMS；不要只看 FFT。" }),
  k("multipath", "多径可生成镜像与鬼影目标", "路径长度与反射几何共同决定", "signal", "nonideal",
    "地面、墙面和车辆形成的间接传播路径会得到错误距离或角度。多径点可与真实点共享速度，却不满足单次反射的空间几何。",
    { details: ["利用道路/墙面几何构造镜像假设。", "联合多帧运动一致性、角度稳定性和幅度特征抑制。"], pitfall: "过强的静态规则可能删掉真实弱目标。" }),

  k("data", "检测后数据处理", "点迹 → 目标 → 航迹 → 事件", "data", "fmcw",
    "检测点需要经过聚类、关联、状态估计与航迹管理，才能形成稳定对象和场景事件。每一级都必须显式传递量测协方差与置信度。"),
  k("clustering", "点云聚类", "空间、速度、幅度联合距离", "data", "data",
    "聚类把同一物理目标产生的多个检测点合并。距离增大时点密度下降、不同维度量纲不同，因此固定欧氏距离通常不够。"),
  k("dbscan", "DBSCAN 用密度连通形成任意形状簇", "ε 邻域 + minPts", "data", "clustering",
    "核心点的 ε 邻域至少含 minPts 个点；密度可达的核心点与边界点构成簇，其余为噪声。无需预设簇数，但单一 ε 难适配距离相关密度。",
    { verification: "按距离、目标类型分桶统计簇纯度、目标召回率、过分裂与误合并。" }),
  k("kmeans", "K-Means 最小化簇内平方距离", "适合近似球状、已知 K 的簇", "data", "clustering",
    "算法交替分配最近中心并更新均值。对初值、离群点和 K 敏感，不适合任意形状或目标数未知的稀疏雷达点云。"),
  k("meanshift", "MeanShift 寻找核密度峰", "带宽决定合并尺度", "data", "clustering",
    "每个点沿核密度梯度移动到局部模态，不需预设簇数。带宽过大导致目标合并，过小导致碎簇，计算量也高于简单 DBSCAN。"),
  k("optics", "OPTICS 用可达距离表达多密度结构", "不强制一次切出固定 ε 的簇", "data", "clustering",
    "OPTICS 生成点的访问顺序和可达距离曲线，可在不同密度阈值下提取簇，适合点密度随距离明显变化的场景。"),
  k("association", "量测与航迹关联", "先门控，再求匹配或概率", "data", "data",
    "关联必须在物理可达范围内判断每个量测属于哪条航迹。拥堵、交叉和漏检会使单一最近邻产生身份切换。"),
  k("mahalanobis-gate", "马氏距离波门考虑协方差", "d²=νᵀS⁻¹ν", "data", "association",
    "创新 ν=z-Hx̂ 的协方差为 S。马氏距离把位置、速度的不确定度标准化，门限可由卡方分布按维数和门概率选择。",
    { formula: "d² = νᵀS⁻¹ν", pitfall: "协方差失真会使波门过紧漏关联或过宽引入组合爆炸。" }),
  k("gnn", "GNN 求全局一对一最小代价匹配", "常用匈牙利算法", "data", "association",
    "Global Nearest Neighbor 在门内构造代价矩阵并求整帧最优匹配。它高效且确定，但仍是硬判决，交叉时一次错误可能持续传播。"),
  k("jpda", "JPDA 对可行关联事件加权", "软关联保留多种解释", "data", "association",
    "JPDA 枚举或近似计算满足互斥约束的联合关联事件，将各量测按边缘关联概率加权更新航迹。它能降低交叉时的硬切换，但相邻目标可能发生航迹合并。",
    { impact: "候选量测和航迹增多时组合数快速增长，工程上常做聚类分解、门控和次优近似。" }),
  k("extended-gate", "扩展目标波门要包含目标外形", "点目标椭圆门不足以覆盖整车散射点", "data", "association",
    "扩展目标可在状态中估计长宽、朝向或随机矩阵，使波门覆盖目标空间占据范围，并将多个量测联合关联到同一目标。"),
  k("estimation", "贝叶斯状态估计", "预测先验 + 量测似然 → 后验", "data", "data",
    "状态估计融合运动模型、过程噪声和量测协方差，递推得到位置、速度、转向率及其不确定度。"),
  k("estimators", "LS、ML、MAP 与 MMSE 的目标不同", "残差 / 似然 / 后验 / 均方误差", "data", "estimation",
    "最小二乘最小化残差；最大似然最大化 p(z|x)；MAP 最大化 p(x|z)；MMSE 取后验均值。高斯线性条件下部分结果重合，非高斯时并不等价。"),
  k("motion-models", "CV、CA、CTRV、CTRA 描述不同机动", "直行 / 加速 / 转弯", "data", "estimation",
    "CV 假设速度近似常量；CA 引入加速度；CTRV 保持转向率和速度；CTRA 同时允许切向加速度。模型复杂度增加也会扩大不可观测状态与调参难度。"),
  k("kf-family", "KF / EKF / UKF 处理不同非线性", "线性解析 / 一阶线性化 / Sigma 点", "data", "estimation",
    "KF 对线性高斯系统给出闭式递推；EKF 用雅可比线性化；UKF 传播一组 sigma 点逼近非线性变换后的均值和协方差。",
    { pitfall: "滤波发散常来自模型、时间戳、坐标变换或协方差设置错误，而非矩阵公式本身。" }),
  k("imm", "IMM 用模型概率融合多种运动假设", "交互 → 并行滤波 → 概率更新", "data", "estimation",
    "IMM 在多个运动模型之间混合初值，并根据各模型创新似然更新模型概率，最后融合状态。它比单模型更快响应机动，但模型集合和转移概率必须可解释。"),
  k("nis-nees", "NIS / NEES 检查统计一致性", "误差应与协方差相匹配", "data", "estimation",
    "NIS 使用创新和 S，无需真实状态；NEES 使用状态估计误差，需要真值。若长期超出卡方置信区间，通常意味着协方差过小或模型失配。"),
  k("track-management", "航迹管理控制生命周期", "起始、确认、保持、删除、融合", "data", "data",
    "航迹管理在确认延迟与虚假航迹率之间折中，并处理短时漏检、交叉、分裂与合并。"),
  k("track-initiation", "M/N 逻辑用于航迹确认", "N 帧内至少 M 次命中", "data", "track-management",
    "候选航迹只有在滑动窗口中满足命中次数才转为确认航迹。M 越大虚假航迹越少，但确认时间更长且弱目标更易被删。"),
  k("track-score", "航迹评分累积检测证据", "命中加分，漏检扣分", "data", "track-management",
    "评分法可把 Pd、Pfa 和关联似然转换为对数似然增量，比固定 M/N 更容易适配不同检测置信度。删除门限应与最大允许遮挡时间一致。"),
  k("tracking-frameworks", "检测后跟踪与联合框架", "TbD / 联合检测关联 / 反馈迭代", "data", "track-management",
    "Tracking-by-detection 接口清晰但丢失阈下信息；联合框架可利用热图或时序特征；检测-跟踪反馈可缩小 ROI，却存在错误自增强风险。"),
  k("extended-dense", "扩展目标与密集场景需要多量测模型", "一个目标可产生多个点", "data", "track-management",
    "随机矩阵、泊松点过程或占据栅格模型能表达目标外形和多量测。密集场景还需显式处理遮挡、目标间相互作用和身份保持。"),
  k("events", "事件由稳定航迹和环境证据触发", "停车、降雨、拥堵", "data", "data",
    "事件判定不应直接使用单帧检测点，而应结合时间窗口、航迹置信度和场景区域约束。"),
  k("stop-event", "停车需要速度滞回与持续时间", "进入阈值和退出阈值分离", "data", "events",
    "用较低速度阈值进入停车状态、较高阈值退出，并要求持续若干秒，可避免速度噪声在阈值附近反复切换。"),
  k("rain-event", "降雨表现为大量低 SNR 弥散点", "多距离、多速度、低持续性", "data", "events",
    "雨滴与路面湿反射可提高点数和噪底。识别应联合点密度、SNR 分布、速度散布、跨帧寿命和环境传感器，避免把人群或树叶误判为雨。"),
  k("congestion-event", "拥堵是区域内低速航迹的群体状态", "密度 + 速度 + 持续时间", "data", "events",
    "在道路 ROI 内统计有效航迹密度和速度分位数，并加入持续时间与车道方向约束。单车停车不等于拥堵。"),

  k("system", "系统与硬件约束", "射频、ADC、阵列、MIMO、组网", "system", "fmcw",
    "系统设计把检测距离、分辨率、视场和刷新率分解到发射功率、带宽、时序、阵列、ADC、计算与同步预算。"),
  k("link-budget", "链路预算决定输入 SNR", "信号功率与噪声功率逐项核算", "system", "system",
    "链路预算需要包含发射功率、天线增益、RCS、传播损耗、接收噪声系数、带宽以及后续处理增益。"),
  k("radar-equation", "单站雷达回波按 R⁻⁴ 衰减", "距离翻倍，功率约降 12 dB", "system", "link-budget",
    "点目标单站雷达方程中，发射路径和接收路径各贡献一次 R² 扩散损耗，因此接收功率与 R⁴ 成反比。RCS、天线方向图和系统损耗同样重要。",
    { formula: "P_r=P_tG_tG_rλ²σ/[(4π)³R⁴L]" }),
  k("noise-figure", "噪声系数描述接收机 SNR 损失", "N=kTBF", "system", "link-budget",
    "热噪声功率由温度 T 和等效噪声带宽 B 决定，噪声系数 F 将理想输入噪声放大。前级 LNA 增益和 NF 对级联噪声最关键。",
    { formula: "P_n=kTBF；NF=10log₁₀F" }),
  k("mimo", "MIMO 用发射正交性构造虚拟阵列", "Ntx×Nrx 个虚拟通道", "system", "system",
    "不同 TX 的回波需要在时间、频率、相位编码或码域上可分离。虚拟阵元位置是 TX 与 RX 位置之和，不是简单把通道编号排列。"),
  k("tdma", "TDMA-MIMO 依次发射不同 TX", "实现简单但运动引入 TX 间相位", "system", "mimo",
    "不同 TX 在不同时刻发射，接收后按 TX 重排为虚拟阵列。运动目标在 TX 时隙间产生额外多普勒相位，若不校正会造成角度偏移或虚拟阵列失配。"),
  k("ddma", "DDMA 用不同多普勒偏移区分 TX", "相位编码使 TX 落入不同 Doppler 区域", "system", "mimo",
    "各 TX 同时发射但在 chirp 间施加不同相位步进，使回波在 Doppler 域分离。需要预留 Doppler 频谱并处理目标速度与编码偏移叠加。"),
  k("fdma-cdma", "FDMA / CDMA 用频率或码区分 TX", "正交性换带宽或处理复杂度", "system", "mimo",
    "FDMA 给不同 TX 分配载频/子带，可能引入不同波长和距离耦合；CDMA 用码序列分离，需要低互相关码和匹配处理。"),
  k("arrays", "阵列几何决定角度可观测性", "孔径、视场、栅瓣、冗余", "system", "system",
    "阵元坐标直接进入导向矢量。均匀阵列便于 FFT，稀疏阵列用更少通道扩大孔径，但会带来非均匀旁瓣和模糊管理。"),
  k("ula", "ULA 的孔径决定主瓣宽度", "孔径越大角分辨率越高", "system", "arrays",
    "对固定波长，增加阵元数或间距可扩大孔径并缩窄波束；但间距超过 λ/2 会压缩无模糊视场并产生栅瓣。"),
  k("sparse-array", "最小冗余与互质阵列利用差分共阵", "少通道获得更多虚拟滞后", "system", "arrays",
    "稀疏阵列通过选择非均匀阵元位置扩大差分共阵自由度。它不免费获得性能：有限快拍、互耦、缺失滞后和旁瓣结构会影响实际测角。"),
  k("rf-adc", "射频与 ADC 共同限定动态范围", "LNA/VGA/HPF/LPF/ADC", "system", "system",
    "接收增益必须让弱目标高于量化噪声，同时给近距离强目标、泄漏和干扰留出削顶余量。"),
  k("sampling", "ADC 采样率必须覆盖有效 IF", "实采样与复采样 Nyquist 区间不同", "system", "rf-adc",
    "采样率选择应基于目标最大拍频、模拟滤波器过渡带和器件数字前端配置。仅满足理论 Nyquist 而没有抗混叠裕量会使边缘目标折叠。"),
  k("enob", "ENOB 比标称位数更接近真实精度", "SINAD→ENOB", "system", "rf-adc",
    "噪声、失真和时钟抖动使有效位数低于 ADC 标称位数。高 IF 下时钟抖动造成的 SNR 限制更明显。",
    { formula: "ENOB=(SINAD−1.76)/6.02" }),
  k("calibration", "校准分为器件自校准与场景校准", "温漂、通道、距离偏置", "system", "rf-adc",
    "芯片内部校准处理 PLL、RX/TX 增益等器件变化；系统仍需用外部目标估计距离偏置和通道幅相。校准参数必须与温度、配置和频段绑定。"),
  k("network", "分布式雷达需要统一时空基准", "时间同步 + 外参 + 融合", "system", "system",
    "多雷达融合前必须统一时间戳、坐标系和量测协方差。同步误差会被目标速度放大为空间误差，外参误差会造成系统性双影。"),
  k("sync", "同步误差 Δt 产生约 vΔt 的位置错位", "高速目标对时间偏差更敏感", "system", "network",
    "软时间戳包含传输与调度抖动，硬件触发或 PTP 可降低误差。融合系统应估计并监控相对时延，而不是假设所有帧天然同时。",
    { formula: "Δx ≈ v·Δt" }),

  k("ai", "AI 与学习方法", "学习难建模部分，不替代物理约束", "ai", "fmcw",
    "学习方法适合处理复杂杂波、时空交互和语义任务，但训练分布、置信度校准和边缘部署必须与经典链路共同验证。"),
  k("learned-front", "学习式前端直接处理 IF 或频谱", "去噪、超分辨、检测", "ai", "ai",
    "网络可从复数 IF、Range-Doppler 图或角谱学习特征。输入表示必须保留相位、标定和物理坐标，否则容易得到只在单一配置有效的纹理分类器。"),
  k("model-driven", "模型驱动网络把算法迭代展开成层", "学习阈值与正则项", "ai", "learned-front",
    "将稀疏重构、近端梯度或滤波迭代展开为有限层网络，可保留数据一致性并减少训练自由度，通常比纯黑盒更容易跨场景解释。"),
  k("learned-cfar", "学习检测器必须固定 Pfa 再比较 Pd", "分类准确率不能替代检测统计", "ai", "learned-front",
    "学习式检测可以利用非均匀背景特征，但输出分数需要校准到可控虚警率。测试集应包含未见天气、路面、干扰和传感器批次。"),
  k("learned-back", "学习式后端建模目标交互与场景", "GNN / Transformer / Occupancy", "ai", "ai",
    "点云、航迹和地图可表示为图或时空序列，模型学习关联、交互和占据变化。应保留几何约束、时间戳和可解释置信度。"),
  k("gnn-association", "GNN 用消息传递学习关联代价", "节点是目标/量测，边是候选关联", "ai", "learned-back",
    "先用物理波门稀疏化候选边，再由 GNN 融合运动、外形、幅度和历史特征输出关联概率，可降低全连接图的组合和泛化风险。"),
  k("occupancy", "占据网络预测网格存在概率", "适合稠密、非点目标场景", "ai", "learned-back",
    "占据表示不强迫每个回波属于一个离散目标，可表达路沿、可行驶空间和被遮挡区域。评价应包含空间 IoU、动态占据误差和概率校准。"),
  k("domain-shift", "域偏移来自天气、安装与硬件差异", "训练分布外性能可能骤降", "ai", "ai",
    "天线罩、安装角、温度、增益配置、城市结构和目标类型都会改变数据分布。需要跨设备/跨场景留出测试、仿真到实测对齐和在线漂移监控。"),
  k("edge-deploy", "边缘部署要联合量化、延迟与精度", "INT8 并不自动保持复数相位信息", "ai", "ai",
    "模型压缩需逐层分析动态范围，使用量化感知训练或校准集。验收应报告端到端帧延迟、峰值内存、功耗和任务指标，而非只报 MAC 数。"),
  k("uncertainty", "模型应输出可校准的不确定度", "知道何时不可信", "ai", "ai",
    "概率分数若未校准，无法直接用于航迹管理或安全策略。可用温度缩放、深度集成或分布外检测，并以 ECE、NLL 和风险-覆盖曲线验证。"),
];

export const crossLinks = [
  { from: "slope", to: "if-band", label: "拍频上移" },
  { from: "range-window", to: "cfar-geometry", label: "主瓣决定保护单元" },
  { from: "channel-calibration", to: "tdma", label: "虚拟通道相位" },
  { from: "multipath", to: "jpda", label: "虚假量测" },
  { from: "ca-cfar", to: "dbscan", label: "检测点" },
  { from: "nis-nees", to: "mahalanobis-gate", label: "协方差一致性" },
  { from: "domain-shift", to: "learned-cfar", label: "阈值失配" },
];

/** Raw LaTeX is deliberately kept separate from display copy so it can be
 * rendered clearly and copied without losing commands or subscripts. */
export const formulaMeta: Record<string, FormulaMeta> = {
  chirp: { latex: String.raw`S=\frac{B}{T_c}`, symbols: [
    { symbol: "S", latex: "S", explanation: "线性调频斜率", unit: "Hz/s" },
    { symbol: "B", latex: "B", explanation: "单个 Chirp 的有效扫频带宽", unit: "Hz" },
    { symbol: "Tc", latex: "T_c", explanation: "Chirp 有效扫频持续时间", unit: "s" },
  ] },
  "tx-phase": { latex: String.raw`s_{\mathrm{tx}}(t)=A\exp\!\left[j2\pi\left(f_0t+\frac{1}{2}St^2\right)\right]`, symbols: [
    { symbol: "A", latex: "A", explanation: "发射复包络幅度" },
    { symbol: "f0", latex: "f_0", explanation: "Chirp 起始频率", unit: "Hz" },
    { symbol: "t", latex: "t", explanation: "Chirp 内快时间", unit: "s" },
    { symbol: "S", latex: "S", explanation: "调频斜率", unit: "Hz/s" },
  ] },
  slope: { latex: String.raw`f_r=\frac{2SR}{c}`, symbols: [
    { symbol: "fr", latex: "f_r", explanation: "由距离产生的拍频", unit: "Hz" },
    { symbol: "R", latex: "R", explanation: "目标径向距离", unit: "m" },
    { symbol: "c", latex: "c", explanation: "真空光速", unit: "m/s" },
    { symbol: "S", latex: "S", explanation: "调频斜率", unit: "Hz/s" },
  ] },
  "range-resolution": { latex: String.raw`\Delta R=\frac{c}{2B}`, symbols: [
    { symbol: "ΔR", latex: "\\Delta R", explanation: "理想距离分辨率", unit: "m" },
    { symbol: "c", latex: "c", explanation: "真空光速", unit: "m/s" },
    { symbol: "B", latex: "B", explanation: "有效调频带宽", unit: "Hz" },
  ] },
  "beat-range": { latex: String.raw`\tau=\frac{2R}{c},\qquad f_b\approx S\tau,\qquad R\approx\frac{cf_b}{2S}`, symbols: [
    { symbol: "τ", latex: "\\tau", explanation: "电磁波往返传播时延", unit: "s" },
    { symbol: "fb", latex: "f_b", explanation: "静止目标拍频", unit: "Hz" },
    { symbol: "R", latex: "R", explanation: "目标径向距离", unit: "m" },
    { symbol: "S", latex: "S", explanation: "调频斜率", unit: "Hz/s" },
  ] },
  "range-doppler-coupling": { latex: String.raw`f_b\approx\frac{2SR}{c}+f_D,\qquad f_D=\frac{2v}{\lambda}`, symbols: [
    { symbol: "fb", latex: "f_b", explanation: "运动目标的总拍频", unit: "Hz" },
    { symbol: "fD", latex: "f_D", explanation: "多普勒频移", unit: "Hz" },
    { symbol: "v", latex: "v", explanation: "目标径向速度", unit: "m/s" },
    { symbol: "λ", latex: "\\lambda", explanation: "载波波长", unit: "m" },
  ] },
  "range-fft": { latex: String.raw`f_k=\frac{kF_s}{N},\qquad R_k=\frac{cf_k}{2S}`, symbols: [
    { symbol: "k", latex: "k", explanation: "距离 FFT 频点索引" },
    { symbol: "Fs", latex: "F_s", explanation: "ADC 采样率", unit: "Hz" },
    { symbol: "N", latex: "N", explanation: "距离 FFT 点数" },
    { symbol: "Rk", latex: "R_k", explanation: "第 k 个距离频点对应的距离", unit: "m" },
  ] },
  "doppler-phase": { latex: String.raw`v=\frac{\lambda\,\Delta\phi}{4\pi T_r}`, symbols: [
    { symbol: "v", latex: "v", explanation: "目标径向速度", unit: "m/s" },
    { symbol: "Δφ", latex: "\\Delta\\phi", explanation: "相邻 Chirp 的目标相位差", unit: "rad" },
    { symbol: "Tr", latex: "T_r", explanation: "相邻 Chirp 起始时刻间隔", unit: "s" },
    { symbol: "λ", latex: "\\lambda", explanation: "载波波长", unit: "m" },
  ] },
  "velocity-ambiguity": { latex: String.raw`v_{\max}=\frac{\lambda}{4T_r}`, symbols: [
    { symbol: "vmax", latex: "v_{\\max}", explanation: "最大无模糊径向速度", unit: "m/s" },
    { symbol: "Tr", latex: "T_r", explanation: "慢时间采样周期", unit: "s" },
    { symbol: "λ", latex: "\\lambda", explanation: "载波波长", unit: "m" },
  ] },
  "ca-cfar": { latex: String.raw`T=\alpha\,\frac{1}{N}\sum_{i=1}^{N}P_i`, symbols: [
    { symbol: "T", latex: "T", explanation: "CUT 的自适应检测门限" },
    { symbol: "α", latex: "\\alpha", explanation: "由目标虚警率与训练单元数确定的门限因子" },
    { symbol: "Pi", latex: "P_i", explanation: "第 i 个训练单元的功率" },
    { symbol: "N", latex: "N", explanation: "有效训练单元数量" },
  ] },
  music: { latex: String.raw`P_{\mathrm{MUSIC}}(\theta)=\frac{1}{\mathbf a^{H}(\theta)\mathbf E_n\mathbf E_n^{H}\mathbf a(\theta)}`, symbols: [
    { symbol: "θ", latex: "\\theta", explanation: "候选到达角", unit: "rad 或 °" },
    { symbol: "a", latex: "\\mathbf a(\\theta)", explanation: "阵列在角度 θ 处的导向矢量" },
    { symbol: "En", latex: "\\mathbf E_n", explanation: "协方差矩阵的噪声子空间特征向量矩阵" },
    { symbol: "H", latex: "(\\cdot)^H", explanation: "复共轭转置" },
  ] },
  "steering-vector": { latex: String.raw`a_m(\theta)=\exp\!\left(j\frac{2\pi p_m\sin\theta}{\lambda}\right)`, symbols: [
    { symbol: "am", latex: "a_m", explanation: "第 m 个阵元的理论复响应" },
    { symbol: "pm", latex: "p_m", explanation: "第 m 个阵元沿阵列轴的位置", unit: "m" },
    { symbol: "θ", latex: "\\theta", explanation: "入射角", unit: "rad 或 °" },
    { symbol: "λ", latex: "\\lambda", explanation: "载波波长", unit: "m" },
  ] },
  "mahalanobis-gate": { latex: String.raw`d^2=\boldsymbol\nu^{T}\mathbf S^{-1}\boldsymbol\nu`, symbols: [
    { symbol: "d²", latex: "d^2", explanation: "量测与航迹预测之间的平方马氏距离" },
    { symbol: "ν", latex: "\\boldsymbol\\nu", explanation: "量测创新向量" },
    { symbol: "S", latex: "\\mathbf S", explanation: "创新协方差矩阵" },
  ] },
  "radar-equation": { latex: String.raw`P_r=\frac{P_tG_tG_r\lambda^2\sigma}{(4\pi)^3R^4L}`, symbols: [
    { symbol: "Pr", latex: "P_r", explanation: "接收回波功率", unit: "W" },
    { symbol: "Pt", latex: "P_t", explanation: "发射功率", unit: "W" },
    { symbol: "Gt/Gr", latex: "G_t,G_r", explanation: "发射与接收天线增益" },
    { symbol: "σ", latex: "\\sigma", explanation: "目标雷达散射截面", unit: "m²" },
    { symbol: "L", latex: "L", explanation: "系统总损耗（线性值）" },
  ] },
  "noise-figure": { latex: String.raw`P_n=kTBF,\qquad \mathrm{NF}=10\log_{10}F`, symbols: [
    { symbol: "Pn", latex: "P_n", explanation: "接收机输入等效噪声功率", unit: "W" },
    { symbol: "k", latex: "k", explanation: "玻尔兹曼常数", unit: "J/K" },
    { symbol: "T", latex: "T", explanation: "系统噪声温度", unit: "K" },
    { symbol: "B", latex: "B", explanation: "等效噪声带宽", unit: "Hz" },
    { symbol: "F", latex: "F", explanation: "线性噪声因子" },
  ] },
  enob: { latex: String.raw`\mathrm{ENOB}=\frac{\mathrm{SINAD}-1.76}{6.02}`, symbols: [
    { symbol: "ENOB", latex: "\\mathrm{ENOB}", explanation: "ADC 有效位数", unit: "bit" },
    { symbol: "SINAD", latex: "\\mathrm{SINAD}", explanation: "信号与噪声加失真比", unit: "dB" },
  ] },
  sync: { latex: String.raw`\Delta x\approx v\,\Delta t`, symbols: [
    { symbol: "Δx", latex: "\\Delta x", explanation: "时间不同步造成的位置错位", unit: "m" },
    { symbol: "v", latex: "v", explanation: "目标速度", unit: "m/s" },
    { symbol: "Δt", latex: "\\Delta t", explanation: "传感器间相对时间偏差", unit: "s" },
  ] },
};
